#https://docs.rundeck.com/docs/learning/howto/using-ansible.html
- name: test playbook
  hosts: all
  tasks:
    - shell: uname -a
      ignore_errors: yes
      register: uname_result
    - debug: msg="{{ uname_result.stdout }}"
